const products = [
    { id: 1, image: "images/black.jpg", alter: "blackWallper", heading: "1st wall", price: "3000 rs" },
    { id: 2, image: "images/blue.jpg", alter: "bluewallper", heading: "2st wall", price: "3500 rs" },
    { id: 3, image: "images/dining.webp", alter: "diningWallper", heading: "3st wall", price: "6000 rs" },
    { id: 4, image: "images/drawing.jpg", alter: "drawingWallper", heading: "4st wall", price: "4000 rs" },
    { id: 5, image: "images/golden.jpg", alter: "goldenwallper", heading: "2st wall", price: "3800 rs" },
    { id: 6, image: "images/green.jpg", alter: "greenWallper", heading: "3st wall", price: "6800 rs" },
    { id: 7, image: "images/black.jpg", alter: "blackWallper", heading: "1st wall", price: "3000 rs" },
    { id: 8, image: "images/blue.jpg", alter: "bluewallper", heading: "2st wall", price: "3500 rs" },
    { id: 9, image: "images/dining.webp", alter: "diningWallper", heading: "3st wall", price: "6000 rs" },
    { id: 10, image: "images/black.jpg", alter: "blackWallper", heading: "1st wall", price: "3000 rs" },
    { id: 11, image: "images/blue.jpg", alter: "bluewallper", heading: "2st wall", price: "3500 rs" },
    { id: 12, image: "images/dining.webp", alter: "diningWallper", heading: "3st wall", price: "6000 rs" },
    { id: 13, image: "images/drawing.jpg", alter: "drawingWallper", heading: "4st wall", price: "4000 rs" },
    { id: 14, image: "images/golden.jpg", alter: "goldenwallper", heading: "2st wall", price: "3800 rs" },
    { id: 15, image: "images/green.jpg", alter: "greenWallper", heading: "3st wall", price: "6800 rs" },
    { id: 16, image: "images/black.jpg", alter: "blackWallper", heading: "1st wall", price: "3000 rs" },
    { id: 17, image: "images/blue.jpg", alter: "bluewallper", heading: "2st wall", price: "3500 rs" },
    { id: 18, image: "images/dining.webp", alter: "diningWallper", heading: "3st wall", price: "6000 rs" },
    { id: 19, image: "images/black.jpg", alter: "blackWallper", heading: "1st wall", price: "3000 rs" },
    { id: 20, image: "images/blue.jpg", alter: "bluewallper", heading: "2st wall", price: "3500 rs" },
    { id: 21, image: "images/dining.webp", alter: "diningWallper", heading: "3st wall", price: "6000 rs" },
    { id: 22, image: "images/drawing.jpg", alter: "drawingWallper", heading: "4st wall", price: "4000 rs" },
    { id: 23, image: "images/golden.jpg", alter: "goldenwallper", heading: "2st wall", price: "3800 rs" },
    { id: 24, image: "images/green.jpg", alter: "greenWallper", heading: "3st wall", price: "6800 rs" },
    { id: 25, image: "images/black.jpg", alter: "blackWallper", heading: "1st wall", price: "3000 rs" },
    { id: 26, image: "images/blue.jpg", alter: "bluewallper", heading: "2st wall", price: "3500 rs" },
    { id: 27, image: "images/dining.webp", alter: "diningWallper", heading: "3st wall", price: "6000 rs" },
    { id: 28, image: "images/black.jpg", alter: "blackWallper", heading: "1st wall", price: "3000 rs" },
    { id: 29, image: "images/blue.jpg", alter: "bluewallper", heading: "2st wall", price: "3500 rs" },
    { id: 30, image: "images/dining.webp", alter: "diningWallper", heading: "3st wall", price: "6000 rs" },
    { id: 31, image: "images/drawing.jpg", alter: "drawingWallper", heading: "4st wall", price: "4000 rs" },
    { id: 32, image: "images/golden.jpg", alter: "goldenwallper", heading: "2st wall", price: "3800 rs" },
    { id: 33, image: "images/green.jpg", alter: "greenWallper", heading: "3st wall", price: "6800 rs" },
    { id: 34, image: "images/black.jpg", alter: "blackWallper", heading: "1st wall", price: "3000 rs" },
    { id: 35, image: "images/blue.jpg", alter: "bluewallper", heading: "2st wall", price: "3500 rs" },
    { id: 36, image: "images/dining.webp", alter: "diningWallper", heading: "3st wall", price: "6000 rs" },
]

export default products;